-- MySQL dump 10.10
--
-- Host: localhost    Database: ilugbom
-- ------------------------------------------------------
-- Server version	5.0.22-log

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `articles`
--

DROP TABLE IF EXISTS `articles`;
CREATE TABLE `articles` (
  `id` int(11) NOT NULL auto_increment,
  `title` varchar(150) NOT NULL default '',
  `urlpath` varchar(150) NOT NULL,
  `tags` varchar(200) default NULL,
  `author_id` int(11) NOT NULL,
  `body` text NOT NULL,
  `created_at` timestamp NOT NULL default CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL,
  `published` tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (`id`),
  KEY `author_id` (`author_id`),
  KEY `published` (`published`),
  KEY `title` (`title`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `articles`
--


/*!40000 ALTER TABLE `articles` DISABLE KEYS */;
LOCK TABLES `articles` WRITE;
INSERT INTO `articles` VALUES (1,'Debian Openssl vulnerability','debian-openssl-vulnerability','debian, openssl, ssh, openssh',1,'Luciano Bello discovered that the random number generator in Debian\'s openssl package is predictable. This is caused by an incorrect Debian-specific change to the openssl package (CVE-2008-0166). As a result, cryptographic key material may be guessable.<br/><br/>\r\n\r\nThis is a Debian-specific vulnerability which does not affect other operating systems which are not based on Debian. However, other systems can be indirectly affected if weak keys are imported into them.<br/><br/>\r\n\r\nIt is strongly recommended that all cryptographic key material which has been generated by OpenSSL versions starting with 0.9.8c-1 on Debian systems is recreated from scratch. Furthermore, all DSA keys ever used on affected Debian systems for signing or authentication purposes should be considered compromised; the Digital Signature Algorithm relies on a secret random value used during signature generation.\r\n','2008-05-23 18:30:00','2008-05-25 03:12:07',0),(2,'KDE4.0 released','kde4.0-released','kde4, kde, release',1,'KDE 4 is the current series of releases of the K Desktop Environment. The first version (4.0.0) of this series was released on 11 January 2008.[1]<br/><br/>\r\n\r\nThe new series includes updates to several of KDE\'s core components, notably a port to Qt 4. It contains a new multimedia API, called Phonon, a device integration framework called Solid and a new style guide and default icon set called Oxygen. It also includes the new desktop and panel user interface tool, called Plasma, which supports desktop widgets, replacing SuperKaramba and similar to Apple\'s Dashboard widgets. The port to Qt 4 will facilitate support for non-X11-based platforms, including Microsoft Windows and Mac OS X. One of the overall goals of KDE 4 is to be more easily portable to different operating systems.','2008-05-23 18:30:00','2008-05-27 01:04:40',0),(3,'Ubuntu 8.04 released','ubuntu-8.04-released','ubuntu, 8.04',1,'Canonical Ltd. announced the upcoming availability of Ubuntu 8.04 LTS Desktop Edition for free download on Thursday 24 April. In related news, Canonical also announced the simultaneous release of Ubuntu 8.04 LTS Server Edition.<br/><br/>\r\n\r\nUbuntu 8.04 Long Term Support (LTS) provides a stable platform for software and hardware vendors, developers and users. With three years of support and maintenance on the desktop, 8.04 LTS is a great choice for large-scale deployment. A substantial and growing ecosystem of free and commercial software built for Ubuntu provides a rich set of choices for desktop users. This is the eighth desktop release of Ubuntu. Ubuntu\'s track record in delivering - on a precise schedule every six months - a commercial operating system that is free, stable, secure and fully supported, remains unique. ','2008-05-24 18:30:00','2008-05-25 03:35:53',1),(4,'GNOME 2.22 released','gnome-2.22-released','gnome, release, desktop',1,'GNOME 2.22 is the latest version of the GNOME Desktop: a popular, multi-platform desktop environment for your computer. GNOME\'s focus is ease of use, stability, and first class internationalization and accessibility support. GNOME is Free and Open Source Software and provides all of the common tools computer users expect of a modern computing environment, such as email, groupware, web browsing, file management, multimedia, and games. Furthermore, GNOME provides a flexible and powerful platform for software developers, both on the desktop and in mobile applications.<br/><br/>\r\n\r\nThe GNOME Desktop is released every six months and contains many new features, improvements, bug fixes, and translations. GNOME 2.22 continues this tradition. To learn more about GNOME and the qualities that distinguish it from other computer desktop environments (such as usability, accessibility, internationalization, and freedom) visit the About GNOME page on our website.<br/><br/>\r\n\r\nJoin us today and see what a difference you can make.<br/><br/>\r\n\r\nGNOME 2.22 includes all of the improvements made in GNOME 2.20 and earlier. You can learn more about the changes that happened in GNOME 2.20 from its release notes.','2008-05-24 18:30:00','2008-05-25 03:27:37',0);
UNLOCK TABLES;
/*!40000 ALTER TABLE `articles` ENABLE KEYS */;

--
-- Table structure for table `events`
--

DROP TABLE IF EXISTS `events`;
CREATE TABLE `events` (
  `id` int(11) NOT NULL auto_increment,
  `title` varchar(150) NOT NULL default '',
  `urlpath` varchar(150) default NULL,
  `agenda` text NOT NULL,
  `description` text NOT NULL,
  `minute_id` int(11) default NULL,
  `venue_id` int(11) default NULL,
  `date` datetime default NULL,
  `speaker_id` int(11) default NULL,
  `event_url` varchar(200) default NULL,
  `upcoming_url` varchar(200) default NULL,
  `flickr_url` varchar(200) default NULL,
  `is_upcoming` tinyint(1) default NULL,
  `published` tinyint(1) NOT NULL default '0',
  `created_at` timestamp NOT NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY  (`id`),
  KEY `minute_id` (`minute_id`),
  KEY `venue_id` (`venue_id`),
  KEY `speaker_id` (`speaker_id`),
  KEY `published` (`published`),
  KEY `title` (`title`),
  KEY `upcoming` (`is_upcoming`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `events`
--


/*!40000 ALTER TABLE `events` DISABLE KEYS */;
LOCK TABLES `events` WRITE;
INSERT INTO `events` VALUES (1,'May 2008 GLUG meet','may-2008-glug-meet','Talks\r\n<ul>\r\n<li>Xen: A brief introduction - Anurag</li>\r\n<li>NRCFOSS- Kenneth</li>\r\n<li>Python: Getting started - Krishnakant</li>\r\n</ul>','<ul>\r\n<li>Anurag P - Xen Modified Linux kernel</li>\r\n<p>He started with a small introduction on Xen Hypervisor and getting started with a debian guest. He demonstrated how to get a base guest working on an ubuntu system running on xen enabled kernel.</p>\r\n\r\n<li>Kenneth G - Activities of NRCFOSS, AU-KBC Chennai</li>\r\n\r\n<p>NRCFOSS is the National Resource Centre for Free / Open Source Software located at AU-KBC Centre in Madras Institute of Technology.</p>\r\n</ul>',1,1,'2008-05-24 00:00:00',1,'http://www.glug-bom.org/foobar','http://upcoming.yahoo.com/?0xdeadbeef','http://flickr.com/photos/foobar/sets/0xdeadbeef',1,0,'2008-05-23 18:30:00'),(2,'Open Street Map workshop','open-street-map-workshop','This February, Schuyler Erle and Mikel Maron held a series of multi-day workshops in several India universities. Researchers, students, and members of the community were invited to participate, learn, and take stewardship of their city. These were very practical, hands-on days, covering the entire toolset of OpenStreetMap and empowering participants to lead the growth of free and open mapping in India. We will map India!','Though India is changing faster than ever before, the use of digital mapping to track the growth of India\'s cities and the transformation of the countryside has not yet fulfilled its potential. Geo data is closely held and inaccessible, too expensive, and simply out of date. The situation is similar throughout the world. But it doesn\'t have to be.<br/><br/>\r\n\r\nOver the past few years, there has been a revolution in cartography and GIS. Through open source software, the Web and the tools of neogeography, these formally specialized disciplines of mapping have been made accessible to anyone with knowledge about their local place. OpenStreetMap is mapping the entire world openly and collaboratively, and coverage is increasing exponentially. These tools are powerful, in some ways outpacing expensive proprietary and closed systems. The barrier of cost no longer exists. The only prerequisite is a will to know, explore and share.',NULL,NULL,'2008-05-26 00:00:00',NULL,'http://www.example.com/event/foo/bar','','http://www.flickr.com/photos/foobar/sets/bar',NULL,1,'2008-05-25 18:30:00'),(3,'December 2002 GLUG meet','december-2002-glug-meet','<ul>\r\n<li>Discussion on gpart and iptables</li>\r\n<li>Talk on Indianization of GNU/Linux</li>\r\n</ul>','This months GLUG meet will take place at the KRESIT, IIT Campus, Mumbai.',NULL,NULL,'2002-12-07 00:00:00',NULL,'','','',NULL,1,'2008-06-06 18:30:00'),(4,'Linux Lunacy Trip 2002','linux-lunacy-trip-2002','Linux Lunacy Trip to the Arnala Beach on the 22nd of December 2002','The GNU/Linux Users Group - Mumbai will oganize a Linux Lunacy Trip to the Arnala Beach on the 22nd of December 2002',NULL,NULL,'2002-12-22 00:00:00',NULL,'','','',NULL,1,'2008-06-06 18:30:00'),(5,'Feb 2003 GLUG meet at Ruparel college','feb-2003-glug-meet-at-ruparel-college','Introduction and working with Emacs and versioning with libtool.','Intro to Emacs and how it can be an effective tool for a variety of purposes to increase productivity and efficiency.<br/><br/>\r\n\r\nA brief introduction to libtool versioning - specifically on picking the correct version number for libraries.',NULL,NULL,'2003-02-09 00:00:00',NULL,'','','',NULL,1,'2008-06-06 18:30:00'),(6,'GLUG meet at GIT, Belgaum - 2003','glug-meet-at-git,-belgaum---2003','Intro to FOSS at GIT Belgaum.','Intro to FOSS at GIT Belgaum.',NULL,NULL,'2003-03-29 00:00:00',NULL,'','','',NULL,1,'2008-06-06 18:30:00'),(7,'April 2003 GLUG meet at HBCSE','april-2003-glug-meet-at-hbcse','meeting up!','meeting up!',NULL,NULL,'2003-04-13 00:00:00',NULL,'','','',NULL,1,'2008-06-06 18:30:00'),(8,'March 2003 GLUG meet at HBCSE','march-2003-glug-meet-at-hbcse','Lecture on Zope and creating web applications with CMF/Plone.','',NULL,NULL,'2003-03-09 00:00:00',NULL,'','','',NULL,1,'2008-06-06 18:30:00'),(9,'May 2003 GLUG meet at HBCSE','may-2003-glug-meet-at-hbcse','Discussion of version control with CVS and demo of IndLinux Milan.','',NULL,NULL,'2003-05-11 00:00:00',NULL,'','','',NULL,1,'2008-06-06 18:30:00'),(10,'June 2003 GLUG meet at Kitab Mahal','june-2003-glug-meet-at-kitab-mahal','Discussion on localisation of GNU/Linux for Malayalam and Distance Education Program being conducted by KRESIT at IIT Bombay.','',NULL,NULL,'2003-06-08 00:00:00',NULL,'','','',NULL,1,'2008-06-06 18:30:00');
UNLOCK TABLES;
/*!40000 ALTER TABLE `events` ENABLE KEYS */;

--
-- Table structure for table `minutes`
--

DROP TABLE IF EXISTS `minutes`;
CREATE TABLE `minutes` (
  `id` int(11) NOT NULL auto_increment,
  `event_id` int(11) NOT NULL,
  `author_id` int(11) NOT NULL,
  `body` text NOT NULL,
  `published` tinyint(1) NOT NULL default '0',
  `created_at` timestamp NOT NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY  (`id`),
  KEY `event_id` (`event_id`),
  KEY `author_id` (`author_id`),
  KEY `published` (`published`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `minutes`
--


/*!40000 ALTER TABLE `minutes` DISABLE KEYS */;
LOCK TABLES `minutes` WRITE;
INSERT INTO `minutes` VALUES (1,1,1,'Minutes for foo event',1,'2008-05-24 16:32:12');
UNLOCK TABLES;
/*!40000 ALTER TABLE `minutes` ENABLE KEYS */;

--
-- Table structure for table `pages`
--

DROP TABLE IF EXISTS `pages`;
CREATE TABLE `pages` (
  `id` int(11) NOT NULL auto_increment,
  `title` varchar(30) NOT NULL default '',
  `urlpath` varchar(30) default NULL,
  `target_url` varchar(280) default NULL,
  `body` text NOT NULL,
  `author_id` int(11) NOT NULL,
  `order_by` int(4) default NULL,
  `published` tinyint(1) NOT NULL default '0',
  `created_at` timestamp NOT NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY  (`id`),
  KEY `title` (`title`),
  KEY `author_id` (`author_id`),
  KEY `order` (`order_by`),
  KEY `published` (`published`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `pages`
--


/*!40000 ALTER TABLE `pages` DISABLE KEYS */;
LOCK TABLES `pages` WRITE;
INSERT INTO `pages` VALUES (1,'Mailing list','mailing-list','','ILUG-BOM mailing list',1,1,1,'2008-05-24 16:34:34'),(2,'Wiki','wiki','','ILUG-BOM wiki',1,2,1,'2008-05-25 18:30:00'),(3,'Resources','resources','','ILUG-BOM resources and documentation.',1,3,1,'2008-05-25 18:30:00'),(4,'Picture gallery','picture-gallery','http://db.ilug-bom.org/pics/','ILUG-BOM picture gallery.',1,4,1,'2008-05-25 18:30:00'),(5,'About us','about-us','','The GNU/Linux Users Group, Mumbai, India, also called ILUG-Bom, is an\r\ninformal mailing list of over 1000 members from all over India, but mostly\r\nfrom Mumbai.<br/><br/>\r\n\r\nWe discuss issues related to promoting, supporting the GNU/Linux OS,\r\nvarious distributions, sharing free/open source resources, have informal\r\nand formal meetings/seminars, organise workshops now and then, etc.<br/><br/>\r\n\r\nBecoming a list member will allow you to post messages to other members of\r\nthe list, and also read all the mails send by others.<br/><br/>\r\n\r\nThe membership to the list is *FREE* of charge, but comes with certain\r\n*RESPONSIBILITIES*. Please read the instructions posted in the first mail\r\ncarefully and follow the rules and regulations carefully.',1,5,1,'2008-05-25 18:30:00');
UNLOCK TABLES;
/*!40000 ALTER TABLE `pages` ENABLE KEYS */;

--
-- Table structure for table `people`
--

DROP TABLE IF EXISTS `people`;
CREATE TABLE `people` (
  `id` int(11) NOT NULL auto_increment,
  `username` varchar(50) NOT NULL default '',
  `password` varchar(45) NOT NULL default '',
  `fullname` varchar(100) NOT NULL default '',
  `nickname` varchar(50) default NULL,
  `irc_nick` varchar(30) default NULL,
  `profile` text NOT NULL,
  `email` varchar(100) NOT NULL default '',
  `webpage` varchar(100) default NULL,
  `flickr_username` varchar(32) default NULL,
  `yahooim_username` varchar(32) default NULL,
  `gtalk_username` varchar(32) default NULL,
  `visible` tinyint(1) NOT NULL default '0',
  `deleted` tinyint(1) NOT NULL default '0',
  `created_at` timestamp NOT NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `username_2` (`username`),
  UNIQUE KEY `email_2` (`email`),
  KEY `username` (`username`),
  KEY `password` (`password`),
  KEY `fullname` (`fullname`),
  KEY `nickname` (`nickname`),
  KEY `email` (`email`),
  KEY `visible` (`visible`),
  KEY `deleted` (`deleted`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `people`
--


/*!40000 ALTER TABLE `people` DISABLE KEYS */;
LOCK TABLES `people` WRITE;
INSERT INTO `people` VALUES (1,'anurag','8843d7f92416211de9ebb963ff4ce28125932878','Anurag','gnurag','devmodem','Hi! I am a GNU/Linux enthusiast.','gnurag@gmail.com','http://web.gnuer.org',NULL,'gnurag','gnurag@gmail.com',1,0,'2008-05-24 10:02:00');
UNLOCK TABLES;
/*!40000 ALTER TABLE `people` ENABLE KEYS */;

--
-- Table structure for table `settings`
--

DROP TABLE IF EXISTS `settings`;
CREATE TABLE `settings` (
  `id` int(11) NOT NULL auto_increment,
  `key` varchar(50) NOT NULL default '',
  `value` varchar(280) default NULL,
  PRIMARY KEY  (`id`),
  KEY `key` (`key`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `settings`
--


/*!40000 ALTER TABLE `settings` DISABLE KEYS */;
LOCK TABLES `settings` WRITE;
INSERT INTO `settings` VALUES (1,'about_site','ILUG-BOM is the website for Indian GNU/Linux users based in and around Mumbai. ILUG-BOM is one of the oldest LUGs existing in India.');
UNLOCK TABLES;
/*!40000 ALTER TABLE `settings` ENABLE KEYS */;

--
-- Table structure for table `venues`
--

DROP TABLE IF EXISTS `venues`;
CREATE TABLE `venues` (
  `id` int(11) NOT NULL auto_increment,
  `short_name` varchar(50) NOT NULL default '',
  `name` varchar(150) NOT NULL default '',
  `organization` varchar(150) NOT NULL default '',
  `urlpath` varchar(30) NOT NULL,
  `locality` varchar(50) NOT NULL default '',
  `address` varchar(200) NOT NULL default '',
  `reaching` text,
  `venue_url` varchar(200) default NULL,
  `contact_person` varchar(30) default NULL,
  `contact_phone` varchar(11) default NULL,
  `published` tinyint(1) NOT NULL default '0',
  `created_at` timestamp NOT NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY  (`id`),
  KEY `address` (`address`),
  KEY `published` (`published`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `venues`
--


/*!40000 ALTER TABLE `venues` DISABLE KEYS */;
LOCK TABLES `venues` WRITE;
INSERT INTO `venues` VALUES (1,'HBCSE','Homi Bhabha Center for Science Education','TIFR','homi-bhabha-center-for-science','Mankhurd','Homi Bhabha Centre for Science Education,  Tata Institute of Fundamental Research,   V.N. Purav Marg, Mankhurd,  Mumbai, 400088 INDIA','Homi Bhabha Centre for Science Education (HBCSE) is located in the North-East of Mumbai near Anushakti Nagar Bus Terminus. Anushakti Nagar Bus Terminus is a landmark known to most taxi/auto drivers. The Centre is immediately adjacent to the terminus on the Eastern side. The following guidelines will help you to reach the Centre either by road or by suburban (local) train from the main entry points to the city.<br/><br/>\r\n\r\nFrom the International (Sahar) and Domestic Airports: You may take a pre-paid taxi to Anushakti Nagar Bus Terminus. The approximate distance is 25 km and the fare is about Rs.250/-. It is always advisable to take a pre-paid taxi from the airport.<br/><br/>\r\n\r\n<ul>\r\n<li>If you alight at CST/VT, buy a ticket to Mankhurd and board the trains marked M, VA, BR, KD or PL. The journey time is approximately 55 minutes. After alighting at Mankhurd get out of the station on the east side and take an auto-rikshaw (three wheeler) to Anushakti Nagar Bus Terminus. Soon after the first right turn you will see HBCSE to your left.</li>\r\n<li>If you alight at Dadar, you may directly take a taxi to Anushaktinagar Bus Terminus or BARC Gate. The taxi fare will be about Rs.120/-. It is not advisable to take the suburban train in the evening after 3pm, specially on a working day. If you wish to come by the suburban train, buy a ticket to Mankhurd, take a train for Kurla station, and then switch over to harbour line train on platform number 7 to reach Mankhurd. After alighting at Mankhurd get out of the station on the east side and take an auto-rikshaw (three wheeler) to Anushakti Nagar Bus Terminus. Soon after the first right turn you will see HBCSE to your left.</li>\r\n\r\n<li>If you alight at Kurla, you may take an auto-rikshaw (three wheeler) to Anushaktinagar Bus Terminus or BARC Gate. Auto fare will be about Rs.30/-. If you wish to come by the local train buy a ticket to Mankhurd and board harbour line train on platform number 7. After alighting at the Mankhurd station, get out of the station on the east side and take an auto-rikshaw (three wheeler) for Anushakti Nagar Bus Terminus. Soon after the first right turn, before reaching the bus terminus, you will see HBCSE to your left.<br/><br/>\r\n\r\nFrom the major Railway Stations: You may keep in mind the following order of proximity from the Centre while alighting: Kurla terminus, Dadar terminus, Bombay Central and CST (Chatrapati Shivaji Terminus or VT for Victoria Terminus), farthest being CST. From each of the stations you may follow the instructions given below to reach the Centre.</li>\r\n\r\n<li>If you alight at Bombay Central, you may take a taxi to Anushakti nagar bus terminus. Taxi fare will be about Rs.150/-. A cheaper option would be to take a suburban train to Bandra, and then take an auto-rikshaw to Anushakti Nagar Bus Terminus. Auto fare from Bandra will be about Rs.60/-. From Bandra you can also board BEST bus, route number 371 directly to the bus terminus.</li>\r\n</ul>\r\nIf you have any problems in reaching HBCSE please call the centre, asking for help.<br/><br/>\r\n\r\nPhones: 2556 7711, 2555 4712, 2555 5242, 2558 0036, 2558 0890. ','http://www.hbcse.tifr.res.in','Alpesh','09989334322',1,'2008-05-24 17:02:00');
UNLOCK TABLES;
/*!40000 ALTER TABLE `venues` ENABLE KEYS */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

