-- MySQL dump 10.11
--
-- Host: localhost    Database: ilugbom
-- ------------------------------------------------------
-- Server version	5.0.45-Debian_1ubuntu3.3-log

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `articles`
--

DROP TABLE IF EXISTS `articles`;
CREATE TABLE `articles` (
  `id` int(11) NOT NULL auto_increment,
  `title` varchar(150) NOT NULL default '',
  `urlpath` varchar(150) NOT NULL,
  `tags` varchar(200) default NULL,
  `author_id` int(11) NOT NULL,
  `body` text NOT NULL,
  `created_at` timestamp NOT NULL default CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL,
  `published` tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (`id`),
  KEY `author_id` (`author_id`),
  KEY `published` (`published`),
  KEY `title` (`title`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `articles`
--

LOCK TABLES `articles` WRITE;
/*!40000 ALTER TABLE `articles` DISABLE KEYS */;
INSERT INTO `articles` VALUES (1,'Debian Openssl vulnerability','debian-openssl-vulnerability','debian, openssl, ssh, openssh',1,'Luciano Bello discovered that the random number generator in Debian\'s openssl package is predictable. This is caused by an incorrect Debian-specific change to the openssl package (CVE-2008-0166). As a result, cryptographic key material may be guessable.<br/><br/>\r\n\r\nThis is a Debian-specific vulnerability which does not affect other operating systems which are not based on Debian. However, other systems can be indirectly affected if weak keys are imported into them.<br/><br/>\r\n\r\nIt is strongly recommended that all cryptographic key material which has been generated by OpenSSL versions starting with 0.9.8c-1 on Debian systems is recreated from scratch. Furthermore, all DSA keys ever used on affected Debian systems for signing or authentication purposes should be considered compromised; the Digital Signature Algorithm relies on a secret random value used during signature generation.\r\n','2008-05-23 18:30:00','2008-05-25 03:12:07',0),(2,'KDE4 released','kde4-released','kde4, kde, release',1,'KDE 4 is the current series of releases of the K Desktop Environment. The first version (4.0.0) of this series was released on 11 January 2008.[1]<br/><br/>\r\n\r\nThe new series includes updates to several of KDE\'s core components, notably a port to Qt 4. It contains a new multimedia API, called Phonon, a device integration framework called Solid and a new style guide and default icon set called Oxygen. It also includes the new desktop and panel user interface tool, called Plasma, which supports desktop widgets, replacing SuperKaramba and similar to Apple\'s Dashboard widgets. The port to Qt 4 will facilitate support for non-X11-based platforms, including Microsoft Windows and Mac OS X. One of the overall goals of KDE 4 is to be more easily portable to different operating systems.','2008-05-23 18:30:00','2008-05-25 18:46:05',1),(3,'Ubuntu 8.04 released','ubuntu-8.04-released','ubuntu, 8.04',1,'Canonical Ltd. announced the upcoming availability of Ubuntu 8.04 LTS Desktop Edition for free download on Thursday 24 April. In related news, Canonical also announced the simultaneous release of Ubuntu 8.04 LTS Server Edition.<br/><br/>\r\n\r\nUbuntu 8.04 Long Term Support (LTS) provides a stable platform for software and hardware vendors, developers and users. With three years of support and maintenance on the desktop, 8.04 LTS is a great choice for large-scale deployment. A substantial and growing ecosystem of free and commercial software built for Ubuntu provides a rich set of choices for desktop users. This is the eighth desktop release of Ubuntu. Ubuntu\'s track record in delivering - on a precise schedule every six months - a commercial operating system that is free, stable, secure and fully supported, remains unique. ','2008-05-24 18:30:00','2008-05-25 03:35:53',0),(4,'GNOME 2.22 released','gnome-2.22-released','gnome, release, desktop',1,'GNOME 2.22 is the latest version of the GNOME Desktop: a popular, multi-platform desktop environment for your computer. GNOME\'s focus is ease of use, stability, and first class internationalization and accessibility support. GNOME is Free and Open Source Software and provides all of the common tools computer users expect of a modern computing environment, such as email, groupware, web browsing, file management, multimedia, and games. Furthermore, GNOME provides a flexible and powerful platform for software developers, both on the desktop and in mobile applications.<br/><br/>\r\n\r\nThe GNOME Desktop is released every six months and contains many new features, improvements, bug fixes, and translations. GNOME 2.22 continues this tradition. To learn more about GNOME and the qualities that distinguish it from other computer desktop environments (such as usability, accessibility, internationalization, and freedom) visit the About GNOME page on our website.<br/><br/>\r\n\r\nJoin us today and see what a difference you can make.<br/><br/>\r\n\r\nGNOME 2.22 includes all of the improvements made in GNOME 2.20 and earlier. You can learn more about the changes that happened in GNOME 2.20 from its release notes.','2008-05-24 18:30:00','2008-05-25 03:27:37',0);
/*!40000 ALTER TABLE `articles` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `events`
--

DROP TABLE IF EXISTS `events`;
CREATE TABLE `events` (
  `id` int(11) NOT NULL auto_increment,
  `title` varchar(150) NOT NULL default '',
  `urlpath` varchar(150) default NULL,
  `agenda` text NOT NULL,
  `description` text NOT NULL,
  `minute_id` int(11) default NULL,
  `venue_id` int(11) default NULL,
  `date` datetime default NULL,
  `speaker_id` int(11) default NULL,
  `event_url` varchar(200) default NULL,
  `upcoming_url` varchar(200) default NULL,
  `flickr_url` varchar(200) default NULL,
  `is_upcoming` tinyint(1) default NULL,
  `published` tinyint(1) NOT NULL default '0',
  `created_at` timestamp NOT NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY  (`id`),
  KEY `minute_id` (`minute_id`),
  KEY `venue_id` (`venue_id`),
  KEY `speaker_id` (`speaker_id`),
  KEY `published` (`published`),
  KEY `title` (`title`),
  KEY `upcoming` (`is_upcoming`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `events`
--

LOCK TABLES `events` WRITE;
/*!40000 ALTER TABLE `events` DISABLE KEYS */;
INSERT INTO `events` VALUES (1,'May 2008 GLUG meet','may-2008-glug-meet','Talks\r\n<ul>\r\n<li>Xen: A brief introduction - Anurag</li>\r\n<li>NRCFOSS- Kenneth</li>\r\n<li>Python: Getting started - Krishnakant</li>\r\n</ul>','<ul>\r\n<li>Anurag P - Xen Modified Linux kernel</li>\r\n<p>He started with a small introduction on Xen Hypervisor and getting started with a debian guest. He demonstrated how to get a base guest working on an ubuntu system running on xen enabled kernel.</p>\r\n\r\n<li>Kenneth G - Activities of NRCFOSS, AU-KBC Chennai</li>\r\n\r\n<p>NRCFOSS is the National Resource Centre for Free / Open Source Software located at AU-KBC Centre in Madras Institute of Technology.</p>\r\n</ul>',1,1,'2008-05-24 00:00:00',1,'http://www.glug-bom.org/foobar','http://upcoming.yahoo.com/?0xdeadbeef','http://flickr.com/photos/foobar/sets/0xdeadbeef',1,1,'2008-05-23 18:30:00');
/*!40000 ALTER TABLE `events` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `minutes`
--

DROP TABLE IF EXISTS `minutes`;
CREATE TABLE `minutes` (
  `id` int(11) NOT NULL auto_increment,
  `event_id` int(11) NOT NULL,
  `author_id` int(11) NOT NULL,
  `body` text NOT NULL,
  `published` tinyint(1) NOT NULL default '0',
  `created_at` timestamp NOT NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY  (`id`),
  KEY `event_id` (`event_id`),
  KEY `author_id` (`author_id`),
  KEY `published` (`published`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `minutes`
--

LOCK TABLES `minutes` WRITE;
/*!40000 ALTER TABLE `minutes` DISABLE KEYS */;
INSERT INTO `minutes` VALUES (1,1,1,'Minutes for foo event',1,'2008-05-24 16:32:12');
/*!40000 ALTER TABLE `minutes` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `pages`
--

DROP TABLE IF EXISTS `pages`;
CREATE TABLE `pages` (
  `id` int(11) NOT NULL auto_increment,
  `title` varchar(30) NOT NULL default '',
  `urlpath` varchar(30) default NULL,
  `body` text NOT NULL,
  `author_id` int(11) NOT NULL,
  `order` int(4) default NULL,
  `published` tinyint(1) NOT NULL default '0',
  `created_at` timestamp NOT NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY  (`id`),
  KEY `title` (`title`),
  KEY `author_id` (`author_id`),
  KEY `order` (`order`),
  KEY `published` (`published`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `pages`
--

LOCK TABLES `pages` WRITE;
/*!40000 ALTER TABLE `pages` DISABLE KEYS */;
INSERT INTO `pages` VALUES (1,'Mailing list','mailing-list','ILUG-BOM mailing list',1,1,1,'2008-05-24 16:34:34');
/*!40000 ALTER TABLE `pages` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `people`
--

DROP TABLE IF EXISTS `people`;
CREATE TABLE `people` (
  `id` int(11) NOT NULL auto_increment,
  `username` varchar(50) NOT NULL default '',
  `password` varchar(45) NOT NULL default '',
  `fullname` varchar(100) NOT NULL default '',
  `nickname` varchar(50) default NULL,
  `irc_nick` varchar(30) default NULL,
  `profile` text NOT NULL,
  `email` varchar(100) NOT NULL default '',
  `webpage` varchar(100) default NULL,
  `flickr_username` varchar(32) default NULL,
  `yahooim_username` varchar(32) default NULL,
  `gtalk_username` varchar(32) default NULL,
  `visible` tinyint(1) NOT NULL default '0',
  `deleted` tinyint(1) NOT NULL default '0',
  `created_at` timestamp NOT NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `username_2` (`username`),
  UNIQUE KEY `email_2` (`email`),
  KEY `username` (`username`),
  KEY `password` (`password`),
  KEY `fullname` (`fullname`),
  KEY `nickname` (`nickname`),
  KEY `email` (`email`),
  KEY `visible` (`visible`),
  KEY `deleted` (`deleted`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `people`
--

LOCK TABLES `people` WRITE;
/*!40000 ALTER TABLE `people` DISABLE KEYS */;
INSERT INTO `people` VALUES (1,'anurag','foobar','Anurag','gnurag','devmodem','','gnurag@gmail.com','http://web.gnuer.org',NULL,NULL,NULL,1,0,'2008-05-24 10:02:00');
/*!40000 ALTER TABLE `people` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `settings`
--

DROP TABLE IF EXISTS `settings`;
CREATE TABLE `settings` (
  `id` int(11) NOT NULL auto_increment,
  `key` varchar(50) NOT NULL default '',
  `value` varchar(280) default NULL,
  PRIMARY KEY  (`id`),
  KEY `key` (`key`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `settings`
--

LOCK TABLES `settings` WRITE;
/*!40000 ALTER TABLE `settings` DISABLE KEYS */;
INSERT INTO `settings` VALUES (1,'about_site','ILUG-BOM is the website for Indian GNU/Linux users based in and around Mumbai. ILUG-BOM is one of the oldest LUGs existing in India.');
/*!40000 ALTER TABLE `settings` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `venues`
--

DROP TABLE IF EXISTS `venues`;
CREATE TABLE `venues` (
  `id` int(11) NOT NULL auto_increment,
  `short_name` varchar(50) NOT NULL default '',
  `name` varchar(150) NOT NULL default '',
  `organization` varchar(150) NOT NULL default '',
  `urlpath` varchar(30) NOT NULL,
  `locality` varchar(50) NOT NULL default '',
  `address` varchar(200) NOT NULL default '',
  `reaching` text,
  `venue_url` varchar(200) default NULL,
  `contact_person` varchar(30) default NULL,
  `contact_phone` varchar(11) default NULL,
  `published` tinyint(1) NOT NULL default '0',
  `created_at` timestamp NOT NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY  (`id`),
  KEY `address` (`address`),
  KEY `published` (`published`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `venues`
--

LOCK TABLES `venues` WRITE;
/*!40000 ALTER TABLE `venues` DISABLE KEYS */;
INSERT INTO `venues` VALUES (1,'HBCSE','Homi Bhabha Center for Science Education','TIFR','hbcse','Mankhurd','Mankhurd, Near Anushaktinagar Depot','Take a rickshaw from mankhurd station.','www.hbcse.tifr.res.in','Alpesh','09989334322',1,'2008-05-24 17:02:40');
/*!40000 ALTER TABLE `venues` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2008-05-25 20:58:42
